In [14]:
!pip install numpy

run or terminal

pip install numpy matplotlib

In [1]:
import numpy as np

- create
- basic operation 
- math operation
- indexing and slicing
boolean filter

In [6]:
np.array([1,2,3,4,5])
print('x')
print('x.shape')

x
x.shape


In [8]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
b = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [11]:
z = [0,1,2,3,4,5,6,7,8,9]
nz = np.array([z]*10)
print(nz)
print(nz.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(10, 10)


- random
- arange
- linspace

In [12]:
np.random.rand(3,3)

array([[0.79832272, 0.65205798, 0.16672658],
       [0.8579105 , 0.27025716, 0.85315709],
       [0.13738793, 0.64979755, 0.69288084]])

In [13]:
r1 = np.random.randint(-5,6, (5,5))
print(r1)

[[-2 -5 -4  3 -4]
 [ 2 -5  3  0 -4]
 [ 4  4 -3 -2 -4]
 [-1  5 -4  3  3]
 [-3 -3  3 -2  4]]


In [19]:
# start, stop, gap
np.arange(0,100,  .6)

array([ 0. ,  0.6,  1.2,  1.8,  2.4,  3. ,  3.6,  4.2,  4.8,  5.4,  6. ,
        6.6,  7.2,  7.8,  8.4,  9. ,  9.6, 10.2, 10.8, 11.4, 12. , 12.6,
       13.2, 13.8, 14.4, 15. , 15.6, 16.2, 16.8, 17.4, 18. , 18.6, 19.2,
       19.8, 20.4, 21. , 21.6, 22.2, 22.8, 23.4, 24. , 24.6, 25.2, 25.8,
       26.4, 27. , 27.6, 28.2, 28.8, 29.4, 30. , 30.6, 31.2, 31.8, 32.4,
       33. , 33.6, 34.2, 34.8, 35.4, 36. , 36.6, 37.2, 37.8, 38.4, 39. ,
       39.6, 40.2, 40.8, 41.4, 42. , 42.6, 43.2, 43.8, 44.4, 45. , 45.6,
       46.2, 46.8, 47.4, 48. , 48.6, 49.2, 49.8, 50.4, 51. , 51.6, 52.2,
       52.8, 53.4, 54. , 54.6, 55.2, 55.8, 56.4, 57. , 57.6, 58.2, 58.8,
       59.4, 60. , 60.6, 61.2, 61.8, 62.4, 63. , 63.6, 64.2, 64.8, 65.4,
       66. , 66.6, 67.2, 67.8, 68.4, 69. , 69.6, 70.2, 70.8, 71.4, 72. ,
       72.6, 73.2, 73.8, 74.4, 75. , 75.6, 76.2, 76.8, 77.4, 78. , 78.6,
       79.2, 79.8, 80.4, 81. , 81.6, 82.2, 82.8, 83.4, 84. , 84.6, 85.2,
       85.8, 86.4, 87. , 87.6, 88.2, 88.8, 89.4, 90

In [20]:
# start, stop, number_of_item
np.arange(0,50, .6)

array([ 0. ,  0.6,  1.2,  1.8,  2.4,  3. ,  3.6,  4.2,  4.8,  5.4,  6. ,
        6.6,  7.2,  7.8,  8.4,  9. ,  9.6, 10.2, 10.8, 11.4, 12. , 12.6,
       13.2, 13.8, 14.4, 15. , 15.6, 16.2, 16.8, 17.4, 18. , 18.6, 19.2,
       19.8, 20.4, 21. , 21.6, 22.2, 22.8, 23.4, 24. , 24.6, 25.2, 25.8,
       26.4, 27. , 27.6, 28.2, 28.8, 29.4, 30. , 30.6, 31.2, 31.8, 32.4,
       33. , 33.6, 34.2, 34.8, 35.4, 36. , 36.6, 37.2, 37.8, 38.4, 39. ,
       39.6, 40.2, 40.8, 41.4, 42. , 42.6, 43.2, 43.8, 44.4, 45. , 45.6,
       46.2, 46.8, 47.4, 48. , 48.6, 49.2, 49.8])

In [21]:
np.linspace(0,50, 10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

arrange attribute
- shape
- dtype
- ndim
- size
 

basic operation
- sum
- mean
- min
- max
- std
- reshape
- transpose
- flatten

In [22]:
x.dtype

NameError: name 'x' is not defined

In [23]:
x.ndim

NameError: name 'x' is not defined

In [24]:
z =np.random.randint(1,5, (3,3,3))
z.ndim

3

In [25]:
z.size

27

In [30]:
a = np.random.rand(2,3)
print(a.sum())
print(a.sum(axis=0))  # column-wise
print(a.sum(axis=1)) # row-wise

print(a.mean())
print(a.max())
print(a.min())
print(a.std())

3.579546752042814
[1.16288842 1.06372862 1.35292971]
[1.44878342 2.13076334]
0.596591125340469
0.8528995298709567
0.3099888948178068
0.18875970297918485


In [ ]:
z = np.random.randint(11,99, (5,5))
print(z)
print('transpose')


print(z.flatten)


In [32]:
a = np.random.randint(1,10,  (4,5))
print(a)
print(a.reshape(20))
print(a.reshape(4,5))
print(a.reshape(2,10))
print(a.reshape(10,2))

[[4 7 6 1 9]
 [1 9 1 9 5]
 [7 7 5 7 5]
 [4 9 4 9 9]]
[4 7 6 1 9 1 9 1 9 5 7 7 5 7 5 4 9 4 9 9]
[[4 7 6 1 9]
 [1 9 1 9 5]
 [7 7 5 7 5]
 [4 9 4 9 9]]
[[4 7 6 1 9 1 9 1 9 5]
 [7 7 5 7 5 4 9 4 9 9]]
[[4 7]
 [6 1]
 [9 1]
 [9 1]
 [9 5]
 [7 7]
 [5 7]
 [5 4]
 [9 4]
 [9 9]]


In [33]:
a = np.array([[1,2],[3,4]])
b = np.array([[6,2],[6,3]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[6 2]
 [6 3]]


In [37]:
# when using 2 matrix , the shape must be the same
print(a + b)
print(a + b)
print(a / b) # element wise division
print(a * b) # element wise multiplication
print(a @ b) # matrix multiplication 
print(a.dot(b)) # matrix multiplication 

[[7 4]
 [9 7]]
[[7 4]
 [9 7]]
[[0.16666667 1.        ]
 [0.5        1.33333333]]
[[ 6  4]
 [18 12]]
[[18  8]
 [42 18]]
[[18  8]
 [42 18]]


In [36]:
# when using matrix and scalar
print(a - 10) # broadcasting
print(a * 10) # broadcasting
print(a / 10 ) # broadcasting
print(a + 10) # 


[[-9 -8]
 [-7 -6]]


In [38]:
# indexing
print(a[0,0])
print(a[-1,-1])

1
4


In [41]:
# slicing
x = np.random.randint(1,10,  (5,5))
print(x)
print(x[:,0]) # first column 
print(x[:,-1]) # last column
print(x[:,:3]) # first 3 column


[[1 3 7 5 4]
 [6 2 8 7 4]
 [3 6 8 2 2]
 [8 8 4 3 8]
 [1 5 1 7 8]]
[1 6 3 8 1]
[4 4 2 8 8]
[[1 3 7]
 [6 2 8]
 [3 6 8]
 [8 8 4]
 [1 5 1]]
